### ISSUE TITLE
模态跳转

### ISSUE THREAD

**Issue by xiafb** [huanglins/VHLNavigation#10]
在我的App 中，模态跳转动画结束后才设置导航栏颜色，在跳转过程中，导航栏则是白色的，Demo 中是没有这个问题，不知道问题出在哪了？

**Comment by huanglins** [comment]
你可以试下最新的demo。  白色是默认的导航栏背景颜色，你可以尝试下设置全局样式。




| |
vincent
邮箱：gvincent@163.com
|

签名由 网易邮箱大师 定制

在2018年06月12日 11:54，xiafb 写道：

在我的App 中，模态跳转动画结束后才设置导航栏颜色，在跳转过程中，导航栏则是白色的，Demo 中是没有这个问题，不知道问题出在哪了？
