### ISSUE TITLE
[self vhl_setNavBarBackgroundAlpha:1.0f];  在 ios10.3模拟器兼容问题，iOS11没有问题。

### ISSUE THREAD

**Issue by chengongwen** [huanglins/VHLNavigation#11]
[self vhl_setNavBarBackgroundAlpha:1.0f];   

当我点击一行后，返回，tableview下滑了大概44像素； 再点击一行，返回，tableview又下滑了大概44像素。
![ques1](https://user-images.githubusercontent.com/9940006/43183514-f789fe34-9017-11e8-949a-1b0946afa64e.jpg)
![ques2](https://user-images.githubusercontent.com/9940006/43183521-fa648764-9017-11e8-85f8-f8866f4704af.jpg)

源码Demo在后面，请测试一下，谢谢大神。

**Comment by chengongwen** [comment]
[Uploading VHLNavigationDemo.zip…]()

**Comment by chengongwen** [comment]
@huanglins

**Comment by chengongwen** [comment]
[VHLNavigationDemo.zip](https://github.com/huanglins/VHLNavigation/files/2226919/VHLNavigationDemo.zip)

**Comment by huanglins** [comment]
看到了

**Comment by huanglins** [comment]
这个问题不是 VHLNavigation 引起的问题，应该是 tableview 内边距自动调整引起的。

![image](https://user-images.githubusercontent.com/10528244/43186662-efe20136-9021-11e8-8d3e-4a193b29a93b.png)

不过这样修改的话，就可以达到你想要的效果了。

**Comment by chengongwen** [comment]
谢谢啦
