### ISSUE TITLE
默认禁止横竖屏

### ISSUE THREAD

**Issue by libern** [huanglins/VHLNavigation#15]
当前只要pod一添加本库，不写任何代码，本来支持横屏的，瞬间失效。

**Comment by huanglins** [comment]
大多数情况下页面是竖屏的，只有个别页面需要横屏。
可以自己重写 viewController 中的横竖屏方法就行了。
`shouldAutorotate`, `supportedInterfaceOrientations`

**Comment by libern** [comment]
有没有办法全局取消这个限制吗？

**Comment by huanglins** [comment]
![cc1ae925-1c15-40e0-b25f-bfaf3a7c11a5](https://user-images.githubusercontent.com/10528244/51877016-8174c400-23a5-11e9-9499-8e3015cc4b84.png)

这是因为我默认在 viewController 中重写了这个方法，后面会考虑直接去掉由自己来管理。目前的话你可以直接导入这个文件，并删除这几个方法，然后自行管理就行了。

**Comment by libern** [comment]
好的，谢谢
