### ISSUE TITLE
上滚后导航栏出现的效果？

### ISSUE THREAD

**Issue by internalG** [huanglins/VHLNavigation#16]
有没有计划实现微信朋友圈里那个向上滚动后导航栏出现的效果？一开始导航栏是透明的，alpha的渐变过程。

**Comment by huanglins** [comment]
现在提供的方法是已经支持的，你可以去看下




| |
vincent
|
|
邮箱：gvincent@163.com
|
在2019年03月15日 17:53，internalG 写道：

有没有计划实现微信朋友圈里那个向上滚动后导航栏出现的效果？一开始导航栏是透明的，alpha的渐变过程。

**Comment by internalG** [comment]
BaseNavigationC 类是已经废弃了吗？我发现继承UINavigationController的子类会有很多问题，尤其是后退手势的边缘减小，和UIPageViewController手势冲突等，觉得后退手势的处理还是交给系统不加干涉的好。

**Comment by huanglins** [comment]
demo 里面的这两个基类只是做参考，不影响直接使用 VHLNavigation 这个组件。但是实际项目开发中，一般都会有相应的 ViewController，NavigationController 来处理一些公共的方法。
另：已经不推荐使用 UIPageViewController 这个系统控件了，这个控件因为内部缓存的问题会导致闪退，这个你可以在网上搜得到，可以参考使用我 [VHLSegment](https://github.com/huanglins/VHLSegment) 中 VHLPageViewController 的实现

**Comment by internalG** [comment]
谢谢。另外似乎不支持storyboard segue？用最简单的    [self vhl_setNavBarHidden:YES/NO];之间跳转，pushViewController就可以，performSegueWithIdentifier不行。
