### ISSUE TITLE
ios  适配出现问题

### ISSUE THREAD

**Issue by chengongwen** [huanglins/VHLNavigation#2]
![560117fec97700b14333aeb275fe1c28](https://user-images.githubusercontent.com/9940006/31939656-daba6a24-b880-11e7-8dce-497486731fa9.jpg)

**Comment by huanglins** [comment]
已经解决了，你再看看~

**Comment by chengongwen** [comment]
ios10  需要设置什么方法，来隐藏系统的返回按钮？我现在没有设置任何方法，系统返回按钮还在
