### ISSUE TITLE
ios10  系统返回按钮依然存在

### ISSUE THREAD

**Issue by chengongwen** [huanglins/VHLNavigation#3]
![img_0046](https://user-images.githubusercontent.com/9940006/31995666-ff95a730-b94a-11e7-8ae9-11e2471f530f.PNG)

**Comment by chengongwen** [comment]
Class _UIBarBackgroundClass = NSClassFromString(@"_UIBarBackground");
            if (_UIBarBackgroundClass != nil) {
                if (![view isKindOfClass:_UIBarBackgroundClass]) {
                    //view.alpha = alpha;
                }
            }
            Class _UINavigationBarBackground = NSClassFromString(@"_UINavigationBarBackground");
            if (_UINavigationBarBackground != nil) {
                if (![view isKindOfClass:_UINavigationBarBackground]) {
                    //view.alpha = alpha;
                }
            }
注释：  //view.alpha = alpha;  就没有问题了，是什么原因

**Comment by chengongwen** [comment]
// _UIBarBackground/_UINavigationBarBackground对应的view是系统导航栏，不需要改变其透明度
            Class _UIBarBackgroundClass = NSClassFromString(@"_UIBarBackground");
            if (_UIBarBackgroundClass != nil) {
                if (![view isKindOfClass:_UIBarBackgroundClass]) {
                    //view.alpha = alpha;
                }
            }
            Class _UINavigationBarBackground = NSClassFromString(@"_UINavigationBarBackground");
            if (_UINavigationBarBackground != nil) {
                if (![view isKindOfClass:_UINavigationBarBackground]) {
                    //view.alpha = alpha;
                }
            }

注释： //view.alpha = alpha; 就没有问题了，是什么原因

**Comment by Xlff** [comment]
@chengongwen 我也是 但是注释掉之后没有效果，你知道原因吗

**Comment by chengongwen** [comment]
注释这一段是可以的

**Comment by chengongwen** [comment]
还是依然存在问题

**Comment by chengongwen** [comment]
怎么隐藏系统的上一视图的系统的返回按钮啊，ios10 系统返回按钮依然存在。。

**Comment by huanglins** [comment]
@chengongwen 好的，马上下个 iOS10 的模拟器测试后给您改。。。 >_<。

**Comment by huanglins** [comment]
@chengongwen 我这边 iOS 9.3 / iOS 10.3.1 / iOS 11.2 的模拟器都跑了一下，没发现这个情况。能否告知下你出现这个情况的当前设备信息。

**Comment by huanglins** [comment]
测试发现只会在 iOS 10.3.1 下出现。现在已经改好了，重新下载来看下吧。。

**Comment by chengongwen** [comment]
好的，谢谢！
