### ISSUE TITLE
存在系统返回箭头图标问题

### ISSUE THREAD

**Issue by LoSenTrad** [huanglins/VHLNavigation#4]
一级页面的时候 就会出现了 iOS 10 系统会出现

http://i2.bvimg.com/594097/c2e27c469b9fc8ca.jpg

https://github.com/LoSenTrad/backBtnTest.git 这是问题demo

**Comment by LoSenTrad** [comment]
[测试.zip](https://github.com/huanglins/VHLNavigation/files/1500457/default.zip)
这是我做的demo 你看看

**Comment by huanglins** [comment]
感谢你的demo，测试发现只会在 iOS 10.3.1 下出现。现在已经改好了，重新下载来看下吧。。
