### ISSUE TITLE
10.3.1返回按钮还是存在显示问题

### ISSUE THREAD

**Issue by LoSenTrad** [huanglins/VHLNavigation#5]
在iOS11和iOS9  没问题. iOS10.3.1的返回按钮依旧存在. 当导航栏没隐藏的时候,push下一个控制器,返回按钮闪一下消失,当导航栏隐藏的时候,push 下一个控制器就会一直显示返回按钮图标.
 
有联系方式么?大神!!!
https://i.loli.net/2017/12/11/5a2e4f06814d0.gif 效果图

**Comment by huanglins** [comment]
出现该问题的地方手动调用下    
`[self.navigationController.navigationBar vhl_setBarBackIndicatorViewHidden:YES];`

更灵活一些。
