### ISSUE TITLE
颜色过渡的方式,返回,导航栏有个闪现的过程

### ISSUE THREAD

**Issue by xiafb** [huanglins/VHLNavigation#6]
原demo,手势控制返回的过程中,开始的瞬间有闪现

**Comment by huanglins** [comment]
是模拟器吗，真机不会有这个情况。




| |
vincent
|
|
邮箱：gvincent@163.com
|

签名由 网易邮箱大师 定制

在2017年12月26日 17:45，xiafb 写道：

原demo,手势控制返回的过程中,开始的瞬间有闪现

**Comment by huanglins** [comment]
已经修复这个问题了，重新下载来看下吧。谢谢反馈！！
