### ISSUE TITLE
发现导航栏按钮存在问题(系统模态出来之后)

### ISSUE THREAD

**Issue by LoSenTrad** [huanglins/VHLNavigation#7]
H5页面 有选择图片 弹出系统的模态图片选择器  模态消失之后 页面的系统导航栏按钮出现了 10.3和11都有出现  看动图
https://i.loli.net/2018/01/26/5a6ad1699fd09.gif

**Comment by huanglins** [comment]
手动调用下隐藏系统返回箭头试试

[self.navigationController.navigationBar vhl_setBarBackIndicatorViewHidden:YES];

**Comment by LoSenTrad** [comment]
试过了  没有效果~




    
    
    



    
        
            
                
                    
                        
                    
                    
                        
                            
                            
                            
                                
                                    邮箱：490790096@qq.com
                                
                        
                    
                
            
        
    


签名由 网易邮箱大师 定制
在2018年01月27日 01:28，vincent 写道： 手动调用下隐藏系统返回箭头试试
[self.navigationController.navigationBar vhl_setBarBackIndicatorViewHidden:YES];

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/huanglins/VHLNavigation","title":"huanglins/VHLNavigation","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/huanglins/VHLNavigation"}},"updates":{"snippets":[{"icon":"PERSON","message":"@huanglins in #7: 手动调用下隐藏系统返回箭头试试\r\n\r\n[self.navigationController.navigationBar vhl_setBarBackIndicatorViewHidden:YES];"}],"action":{"name":"View Issue","url":"https://github.com/huanglins/VHLNavigation/issues/7#issuecomment-360849871"}}}
