### ISSUE TITLE
如果是继承自UITableViewController的视图控制器，在进入和返回时导航栏上的内容会向下偏移

### ISSUE THREAD

**Issue by zxFlyer** [huanglins/VHLNavigation#9]
如果是继承自UITableViewController的视图控制器，在进入和返回时的滑动过程中导航栏上的内容会向下偏移，偏移量是导航栏的高度，滑动动画结束后就恢复到了导航栏的位置上

**Comment by huanglins** [comment]
已经修复了这个问题，请重新下载来看下。。
